### PR TITLE
feat: support bsc

### PR DESCRIPTION
**Pull request by xzjcool**
Support for Binance Smart Chain. 
Hope you can merge this pr

### CODE REVIEW

**Comment by rkalis** [comment]
Hey! Thanks for this PR. I wouldn't have thought it would be this easy, but I guess that makes sense since Etherscan and BSCscan are the same company.

Do you maybe have a link to some repository with a Truffle project connecting to BSC so I can try it out?

**Comment by xzjcool** [comment]
Yes, I already tried it.
I run your test and verified
https://www.bscscan.com/address/0xa40da34619d4f95fdde3d5fceedeaa0a438219eb#code

**Comment by rkalis** [comment]
Great, thanks! Just out of curiosity, what did your truffle-config.js file look like when you deployed / verified the example on bsc?

**Comment by xzjcool** [comment]
```
bscMainnet: {
      provider: () => {
        return new HDWalletProvider(`${process.env.MNEMONIC}`, `https://bsc-dataseed.binance.org`)
      },
      gas: 0x7a1200,
      network_id: 56,
      skipDryRun: true
    }
```

**Comment by rkalis** [comment]
Awesome. I love how easy that is. Thanks for the contribution. I want to see if I can get the fix to #49 included in the same release, so I'll wait a few days and then release a new version with this included! 👍

**Comment by xzjcool** [comment]
```
 bscTestnet: {
      provider: () => {
        return new HDWalletProvider(`${process.env.MNEMONIC}`, `https://data-seed-prebsc-1-s1.binance.org:8545`)
      },
      gas: 0x7a1200,
      network_id: 97,
      skipDryRun: true
    }
```
Thank you very much. btw, this is for testnet. @rkalis  you build a very cool library.

**Comment by rkalis** [comment]
This was included in the new 0.5.3 release, thanks again for your contribution!

**Pull request merged**
