### PR TITLE
Merge v0.6.0 (EtherScan Split) w/ Truffle Plugin Verify

### PR DESCRIPTION
**Pull request by Mentors4EDU**
I'm not sure if this is the proper way to merge them together, so please check.
**Still to-do:** Create blockscout verify config files

### CODE REVIEW

**Review by Mentors4EDU — COMMENTED** [review]
Still waiting for Ethereum Classic compatibility

**Review by Mentors4EDU — COMMENTED** [review]
Looking good

**Review by Mentors4EDU — COMMENTED** [review]
Where is Ethereum Classic in this?

**Comment by rkalis** [comment]
@Mentors4EDU I definitely haven't forgotten about this, but adding the blockscout support and further pulling apart the code is a big undertaking, and the code I wrote for this last year is outdated and needs to be reworked. 

So in the code that I wrote at the time there's no mention of ETC or Blockscout yet since it only included the refactoring of that code that made it possible to support multiple endpoints (either Etherscan or Blockscout), but no actual implementation of Blockscout (ETC) verification.

I don't see myself having the time to get into this any time soon though.

One interesting alternative that coiuld be looked into rather than reviving this old code would be to add Sourcify support to the current code base, which I imagine won't super difficult. Blockscout can automatically pull the source code from sourcify iirc so that's maybe the easiest fix to get Blockscout support (without *actually* implementing Blockscout support).

Having said that I don't know when I can find the time for that, but if you want to look into raising a PR for that, it's probably an easier task than getting this old code up to date and getting proper Blockscout support implemented.

**Comment by rkalis** [comment]
Actually I think I'm going to have to close this merge PR since the code in the v0.6.0 branch and the master branch have deviated too much, so if we want to get that functionality in, we'll need to refactor the entire v0.6.0 branch, which needs a lot more manual work, which needs to happen outside of this PR.

But as I said, it's a significant undertaking and I don't think I'll be able to do this in a short time frame.

**Pull request closed without merging**
