### PR TITLE
Added support for Moonriver Network

### PR DESCRIPTION
**Pull request by albertov19**
This PR adds support for Moonriver Network: https://moonbeam.network/

Moonriver is a Ethereum compatible environment in the Kusama Ecosystem, Moonbeam being the similar network for Polkadot (will submit the PR for Moonbeam when available). I followed the Avalanche commit as a reference.

The modifications were tested successfully:

image

You can check here: https://moonriver.moonscan.io/address/0x3d789e518febbeA1c434f3598e1c4F6b73ccC591#code

### CODE REVIEW

**Comment by rkalis** [comment]
Very nice! Is there any testnet that also supports verification that we should include in the same PR?

**Comment by albertov19** [comment]
Yes there is :) - it is called Moonbase Alpha. Unfortunately, the Etherscan team is solving an issue with TestNets API keys that has not been solved yet, so it would not work. To summarize, we have two MainNets (Moonbeam not being live yet), and they mapped Moonbeam API Keys (which you can't get yet) for Moonbase Alpha.

Once they fix the issue I'll create another PR, but we've had this feature requested by developers already for Moonriver. Consequently, this PR :)

**Comment by albertov19** [comment]
Hey @rkalis - any news? Feel free to request any changes you think are important to get this approved ;)

**Comment by rkalis** [comment]
Hey @albertov19, sorry for dropping the ball! Will get this merged and released today!

**Comment by albertov19** [comment]
Thanks!!

**Pull request merged**
