### PR TITLE
Add Cronos Mainnet support

### PR DESCRIPTION
**Pull request by nozeroctnellav7**

### CODE REVIEW

**Comment by nozeroctnellav7** [comment]
[README.md](https://github.com/rkalis/truffle-plugin-verify/files/8372015/README.md)

**Comment by NotEternal** [comment]
@nozeroctnellav7 what about these places:
`/util.js`
- 153 line: `const getApiKey = (...`
- 170 line: `const getApiKeyForPlatform = (...`

**Comment by nozeroctnellav7** [comment]
> @nozeroctnellav7 what about these places: `/util.js`
> 
> * 153 line: `const getApiKey = (...`
> * 170 line: `const getApiKeyForPlatform = (...`

I'm sorry about that. Updated! Thank you.

**Comment by rkalis** [comment]
Thanks guys. Merged + published to npm!

**Pull request merged**
